# Generated by Django 5.0.2 on 2024-05-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categories",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Desktop", "Desktop"),
                            ("Laptop", "Laptop"),
                            ("Phone", "Phone"),
                            ("Accessories", "Accessories"),
                        ],
                        default=False,
                        max_length=100,
                        null=True,
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("price", models.FloatField()),
                ("digital", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="static/images"),
                ),
            ],
        ),
    ]
